"""
Auralis - Raga and Mood Constants
"""

COMMON_RAGAS = [
    "Yaman",
    "Bhairav",
    "Todi",
    "Bilawal",
    "Khamaj",
    "Kafi",
    "Marwa",
    "Poorvi",
    "Bhairavi",
    "Darbari",
    "Malkauns",
    "Bageshri",
    "Jaunpuri",
    "Asavari",
    "Bhimpalasi",
    "Desh",
    "Durga",
    "Hamsadhwani",
    "Kedara",
    "Shankara",
    "Pilu",
    "Ahir Bhairav",
    "Bhoopali",
    "Desi",
    "Lalit",
    "Madhuvanti",
    "Megh",
    "Multani",
    "Puriya Dhanashree",
    "Sohini",
    "Bageshree",
    "Bihag",
    "Chhayanat",
    "Gaud Malhar",
    "Gaur Sarang",
    "Hindol",
    "Jaijaiwanti",
    "Jog",
    "Jogiya",
    "Kamod",
    "Kedar",
    "Kirvani",
    "Mian Ki Malhar",
    "Nayaki Kanada",
    "Patdeep",
    "Puriya",
    "Puriya Kalyan",
    "Rageshree",
    "Shree",
    "Sindhu Bhairavi",
    "Tilak Kamod",
    "Tilang",
    "Vrindavani Sarang",
    "Bairagi",
    "Bhatiyar",
    "Bhinna Shadja",
    "Charukeshi",
    "Gorakh Kalyan",
    "Gujari Todi",
    "Hemant",
]

AI_MOODS = [
    "Meditative",
    "Romantic",
    "Devotional",
    "Energetic",
    "Melancholic",
    "Joyful",
    "Peaceful",
    "Intense",
    "Mysterious",
    "Spiritual",
    "Calm",
    "Uplifting",
    "Sad",
    "Focus",
    "Relaxation",
]
